server:
  port: 8080
  dataPath: 'http://localhost:8080/data/fetch-csv' # 后缀 "/data/fetch-csv"

spring:
  application:
    name: springboot-demo
  thymeleaf:
    cache: false # 关闭缓存
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 日志格式
logging:
  config: classpath:logback.xml
  level:
    com.lucky.spring_boot_demo: trace

# 样本数据集网址
sample-data-path:
  # 豆瓣读书Top250
  doubanBookPath: "classpath:sampleData/douban-books.csv"
  # 猫眼电影榜单
  maoyanFilmPath: "classpath:sampleData/maoyan-films.csv"
  # Metacritic游戏
  metacriticGamePath: "classpath:sampleData/metacritic-games.csv"
  # 随机生成的误差数据
  randomDataPath: "classpath:sampleData/random_data_with_nulls.csv"

# Python编译器配置
python-scripts-path:
  # 解释器路径 ！！！根据自身配置修改！！！
  pythonPath: "D:/Software/Pythons/3.13/python.exe"
  # TODO 数据预处理脚本
  dataVizPath: "src/main/resources/python-scripts/dataViz.py"
